services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/faculty_db
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:8.2.9-noble
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
